### ISSUE TITLE
using grillo data directly on AWS

### ISSUE THREAD

**Issue by mdenolle** [grillo/openeew-python#5]
Hi!

Could you create guidelines to work on the grillo data directly on EC2? i guess we can use aws s3 or boto3, but having some file readers to directly process on AWS would be great.

Cheers,
Marine

**Comment by mallmanj** [comment]
Hi Marine,

Thanks for your question. Do you have an example of the kind of processing you'd like to do, and what sort of time ranges? The openeew python package currently uses a mixture of boto3 and aioboto3 (the latter being used to download files asynchronously, which gives a performance improvement).

Regards
Michael

**Comment by andygrillo** [comment]
This is now documented in the opening paragraph https://openeew.com/docs/historic-data 

Will close out this issue :)
